### ISSUE TITLE
Format method does not obey the arguments that print.data.frame passes to it

### ISSUE THREAD

**Issue by adrfantini** [pacificclimate/PCICt#2]
Hi, this is something that came up in this `stars` issue: https://github.com/r-spatial/stars/issues/410#issuecomment-815584014

Apparently the `PCICt` [format](https://github.com/pacificclimate/PCICt/blob/94ccde33f42bbd408b32344db186d3782c675e87/R/PCICt.R#L300) method does not conform to the arguments expected by `print.data.frame`. This prevents properly using `PCICt` in serveral usecases concerning data frames.

**Comment by jameshiebert** [comment]
A close read of the code indicates that this only affects dates with a 360 degree calendar, since the formatting parameters are only passed through to `PCICt` code [in one instance](https://github.com/pacificclimate/PCICt/blob/94ccde33f42bbd408b32344db186d3782c675e87/R/PCICt.R#L305). In [other](https://github.com/pacificclimate/PCICt/blob/94ccde33f42bbd408b32344db186d3782c675e87/R/PCICt.R#L308) [instances](https://github.com/pacificclimate/PCICt/blob/94ccde33f42bbd408b32344db186d3782c675e87/R/PCICt.R#L320) formatting parameters are passed through to native R functions.

I've written a patch that passes the formatting parameters through to R's native format() method for 360 day calendars, that I believe addresses this issue.

You're welcome to try out the patch with `devtools:::install_github('pacificclimate/PCICt') if you'd like to try it out before the next release.
